### ISSUE TITLE
Finding mac-vendor.txt

### ISSUE THREAD

**Issue by rahrah** [royhills/arp-scan#107]
Hi,

I'm having trouble finding the `mac-vendor.txt` file when compiling from git.

I compiled a2e52db64 (11nov22) today under `slackware-current` with these options:

```
./configure \
  --prefix=/usr \
  --libdir=/usr/lib64 \
  --mandir=/usr/man \
  --disable-static \
  --build=x86_64-slackware-linux
```
This resulted in a binary that could not find the `mac-vendor.txt` file.

I experimented with variations of these:

```
--sysconfdir=/usr/xxx
--datarootdir=/usr/yyy
```
The `mac-vendor.txt` file always looked in a directory higher than where the
file was located.  Nothing seemed to work until I:

1) Used only this option:

`--sysconfdir=/usr/share`

and

2) Used this patch:

```
diff -u arp-scan.c.org arp-scan.c
--- arp-scan.c.org 2022-11-11 11:48:30.000000000 +0000
+++ arp-scan.c  2022-11-23 18:10:43.780106623 +0000
@@ -376,7 +376,7 @@
                   count, fn);
       free(fn);
 
-      fn = get_mac_vendor_filename(macfilename, PKGSYSCONFDIR, MACFILENAME);
+      fn = get_mac_vendor_filename(macfilename, PKGDATADIR, MACFILENAME);
       count = add_mac_vendor(fn);
       if (verbose > 1 && count > 0)
          warn_msg("DEBUG: Loaded %d MAC/Vendor entries from %s.",
```

This essentially reverted the changes c6e112e2f made to `arp-scan.c`.

I'm probably missing something here; if so, I'm sorry for the noise.

Thank you for all your work on `arp-scan` and for making it GPL'd open source software.

===Rich

**Comment by royhills** [comment]
The location of `mac-vendor.txt` was changed in pull request https://github.com/royhills/arp-scan/pull/91, which changed the location from `$(sysconfdir)/$(PACKAGE)` instead of `$(pkgdatadir)`.

This was to make it a "configuration file" that would be preserved between updates because some users use it like a MAC address hosts file.  That's not really it's purpose, but it's a valid use case.

Please let me know if this new location causes any issues.  Issues are always welcome, so thank you for trying arp-scan and taking the time to raise an issue.

**Comment by rahrah** [comment]
Hi,

Thanks for getting back to me.

Forgive me for asking what might be obvious to others, but is it intentional that after a build using commands like the following, I get an error on invocation of arp-scan?

```
git clean -fxd
autoreconf -ivf
./configure \
  --prefix=/usr \
  --libdir=/usr/lib64 \
  --mandir=/usr/man \
  --sysconfdir=/usr/etc \
  --datarootdir=/usr/share/arp-scan \
  --build=x86_64-slackware-linux 

make -j8  
make install
```
I get the following files and directories:

```
/usr/etc/arp-scan/mac-vendor.txt
/usr/share/arp-scan/arp-scan/ieee-oui.txt
```

On invocation I get:

```
arp-scan --interface=eth0 192.168.1.0/24
Interface: eth0, type: EN10MB, MAC: 08:00:27:XX:XX:XX, IPv4: 10.0.2.15
WARNING: Cannot open MAC/Vendor file /usr/etc/mac-vendor.txt: No such file or directory
Starting arp-scan 1.9.9 with 256 hosts (https://github.com/royhills/arp-scan)
```
To surpress the error, I either need to copy `/usr/etc/arp-scan/mac-vendor.txt` to `/usr/etc` or use the `-m` option?

If I just use:

```
autoreconf -ivf

./configure \
  --prefix=/usr \
  --libdir=/usr/lib64 \
  --mandir=/usr/man \
  --build=x86_64-slackware-linux

make -j8  
make install
```

With the `.txt` files here:

```
/usr/share/arp-scan/ieee-oui.txt
/usr/etc/arp-scan/mac-vendor.txt
```

I get this error:

```
WARNING: Cannot open MAC/Vendor file /usr/etc/mac-vendor.txt: No such file or directory
```

My feeling would be that the upstream configuration file(s) should be created in the correct place for `arp-scan` to use them out of the box, iff the files do not already exist exist.  Otherwise just create a obviously named backup of the files in the correct place.  Of course, vendors can choose to do this in the package scripts, and fixes don't seem that hard.  Also, it seems that app related directories in ` /usr/etc` for example, `/usr/etc/arp-scan` should be the correct place to look for the `mac-vendor.txt` file, rather than just `/usr/etc/mac-vendor.txt.`

Once again, thanks for getting back to me, and for all the work you put into this utility.  Forgive me if this is all just my ineptitude.

===Rich

**Comment by royhills** [comment]
No I would not expect it to be possible to configure arp-scan so that it cannot find mac-vendor.txt after a make install. That looks like a regression to me, but I'll need to investigate before I can determine the reason for the behaviour that you are seeing.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rahrah** [comment]
Thanks for this!

**Comment by royhills** [comment]
This is confirmed as a bug. `Makefile.am` is not including `$(PACKAGE)` in the definition for the macro `PKGSYSCONFDIR`.  This is causing `arp-scan` to look for `mac-vendor.txt` in the wrong directory.

The proposed fix is:

```
rsh@bookworm:~/arp-scan$ git diff Makefile.am
diff --git a/Makefile.am b/Makefile.am
index ba8b78d..22334a5 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -1,7 +1,7 @@
 # Process this file with automake to produce Makefile.in
 #
 pkgsysconfdir = $(sysconfdir)/$(PACKAGE)
-AM_CPPFLAGS = -DPKGDATADIR=\"$(pkgdatadir)\" -DPKGSYSCONFDIR=\"$(sysconfdir)\"
+AM_CPPFLAGS = -DPKGDATADIR=\"$(pkgdatadir)\" -DPKGSYSCONFDIR=\"$(sysconfdir)/$(PACKAGE)\"
 #
 bin_PROGRAMS = arp-scan
 #
```

This change hasn't been applied to github yet.

**Comment by rahrah** [comment]
This worked for me.

I applied  the patch in my build script, and all worked as it should,

Thank you for looking into this.
