### ISSUE TITLE
arp-scan 1.9 crashes when running without root permissions

### ISSUE THREAD

**Issue by itamarjp** [royhills/arp-scan#13]
more info at
https://bugzilla.redhat.com/show_bug.cgi?id=1359953

$ arp-scan
Segmentation fault (core dumped)

does it supposed to work without root permissions ?

**Comment by royhills** [comment]
It won't work without root permissions, but it shouldn't throw a segmentation fault.

Are you using the latest version from github?  This is what I get when I run it on Debian Jessie as a non-privileged user:

rsh@jessie:~/arp-scan$ ./arp-scan
ERROR: Cannot open raw packet socket
socket: Operation not permitted

**Comment by xmrbrz** [comment]
The package was created with the latest version of this github repository. 

SRPM: https://kojipkgs.fedoraproject.org//packages/arp-scan/1.9/1.fc24/src/

[xmrbrz@laptop codes]$ arp-scan
Segmentation fault (core dumped)
[xmrbrz@laptop codes]$ 
[xmrbrz@laptop codes]$ 
[xmrbrz@laptop codes]$ arp-scan -V
arp-scan 1.9

Copyright (C) 2005-2013 Roy Hills, NTA Monitor Ltd.
arp-scan comes with NO WARRANTY to the extent permitted by law.
You may redistribute copies of arp-scan under the terms of the GNU
General Public License.
For more information about these matters, see the file named COPYING.

libpcap version 1.7.4
$Id: arp-scan.c 19582 2013-04-28 17:11:17Z rsh $
$Id: error.c 19550 2013-04-15 09:24:42Z rsh $
$Id: wrappers.c 19550 2013-04-15 09:24:42Z rsh $
$Id: utils.c 19550 2013-04-15 09:24:42Z rsh $
$Id: link-packet-socket.c 19578 2013-04-25 15:44:27Z rsh $

**Comment by royhills** [comment]
Could you let me know the OS version and architecture, and I'll try to reproduce.

The output from "uname -a" and "lsb_release -a" is probably enough.

**Comment by xmrbrz** [comment]
Sure.

[xmrbrz@laptop ~]$ uname -a
Linux laptop.xmrbrz 4.6.4-301.fc24.x86_64 #1 SMP Tue Jul 12 11:50:00 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[xmrbrz@laptop ~]$ 
[xmrbrz@laptop ~]$ 
[xmrbrz@laptop ~]$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 24 (Twenty Four)
Release:	24
Codename:	TwentyFour

**Comment by royhills** [comment]
Hmm, I'm having problems reproducing this.  Here's what I've tried and what I get:

1. Installed Fedora 24 x64 in a VMware VM.
Selected "Server" when installing, as I don't need a desktop enviornment, but that probably doesn't make much difference.

2. Installed additional packages:
$ sudo dnf group install "Development Tools"
$ sudo dnf install autoconf automake
$ sudo dnf install libpcap libpcap-devel

3. Install arp-scan from github
$ git clone https://github.com/royhills/arp-scan.git
$ cd arp-scan
$ autoreconf --install
$ ./configure
$ make

4. Run arp-scan
$ ./arp-scan --localnet
ERROR: Cannot open raw packet socket
socket: Operation not permitted
$ sudo ./arp-scan --localnet
Interface: ens33, datalink type: EN10MB (Ethernet)
Starting arp-scan 1.9.2 with 256 hosts (http://www.nta-monitor.com/tools-resources/security-tools/arp-scan/)
192.168.159.2   00:50:56:fd:76:83       VMware, Inc.
192.168.159.1   00:50:56:c0:00:08       VMware, Inc.
192.168.159.131 00:0c:29:7e:8b:31       VMware, Inc.
192.168.159.254 00:50:56:ff:df:4c       VMware, Inc.

7 packets received by filter, 0 packets dropped by kernel
Ending arp-scan 1.9.2: 256 hosts scanned in 5.049 seconds (50.70 hosts/sec). 4 responded

That's what I'd expect: it gives an error if run w/o root, and runs OK as root.

**Comment by itamarjp** [comment]
Can you test installing arp-scan package ?
$ sudo dnf install arp-scan 

it can be caused by some different settings during compile time, here are the logs used during generation of the package.

https://kojipkgs.fedoraproject.org//packages/arp-scan/1.9/1.fc24/data/logs/x86_64/

**Comment by itamarjp** [comment]
I did a new build based on git repo and this problem doesn't happen anymore.

http://koji.fedoraproject.org/koji/taskinfo?taskID=15040900

**Comment by itamarjp** [comment]
probably fixed here, 

https://github.com/royhills/arp-scan/commit/195ff60b98696e822c4a877523b2097d40386cc1

**Comment by itamarjp** [comment]
I have upgraded fedora package to git version, closing this, thank you.
