### ISSUE TITLE
Potential memory leak in arp-scan/arp-scan.c

### ISSUE THREAD

**Issue by icy17** [royhills/arp-scan#138]
Potential memory leak in [arp-scan.c](https://github.com/royhills/arp-scan/blob/master/arp-scan.c#L334) line 334. Calling pcap_compile() without calling pcap_freecode() to free the memory will cause a memory leak.
 [Doc](https://www.tcpdump.org/manpages/pcap_freecode.3pcap.html) says "pcap_freecode() is used to free up allocated memory pointed to by a bpf_program struct generated by [pcap_compile](https://www.tcpdump.org/manpages/pcap_compile.3pcap.html)(3PCAP) when that BPF program is no longer needed, for example after it has been made the filter program for a pcap structure by a call to [pcap_setfilter](https://www.tcpdump.org/manpages/pcap_setfilter.3pcap.html)(3PCAP)."
![image](https://user-images.githubusercontent.com/39425646/216514068-db6d94a8-ebdd-4d39-8025-42f4e1baed7c.png)

**Comment by royhills** [comment]
PR: https://github.com/royhills/arp-scan/pull/139

**Comment by royhills** [comment]
I think this issue is fixed now.  Thanks for the report.
