### ISSUE TITLE
Segmentation on vsnprintf in uClibc.

### ISSUE THREAD

**Issue by nihilus** [royhills/arp-scan#14]
Here is a fix:

```
-         warn_msg("WARNING: \"%s\" is not a valid IPv4 address - target ignored");
+         warn_msg("WARNING: \"%s\" is not a valid IPv4 address - target ignored", host_name);

```

**Comment by royhills** [comment]
I don't know how I could have missed such an obvious error.  Thanks for spotting it.

It's fixed in the latest git commit.

**Comment by nihilus** [comment]
@royhills I tell you why: because on x86 with GNU libc vsnprintf will check what is on the stack and use it as an argument; hence you will get a correct error message in most cases.
