### ISSUE TITLE
configure checks compiling test code should include stdlib.h

### ISSUE THREAD

**Issue by rofl0r** [royhills/arp-scan#17]
from config.log
```
configure:4969: checking whether long long int is 64 bits
[cross-compile branch is taken]
configure:5027: i486-linux-musl-gcc -L/home/sabotage/www/building/lib -isystem ...
conftest.c:58:1: warning: return type defaults to 'int' [-Wreturn-type]
conftest.c: In function 'main':
conftest.c:59:3: warning: implicit declaration of function 'exit' [-Wimplicit-function-declaration]
conftest.c:59:3: warning: incompatible implicit declaration of built-in function 'exit' [enabled by default]
```
exit() is declared by stdlib.h, but on GLIBC it somehow gets magically pulled in when including stdio.h, which is a namespace violation. on musl not, and so this warning is raised.
that would mean if i have -Werror-implicit-function-declaration in my CFLAGS, the configure check would fail because of that warning and the result would be misinterpreted, either giving me a broken build or not even letting me get there.

unfortunately i was not able to find where in configure.ac the code to compile in the cross-compile scenario comes from, so i couldnt make a PR.

**Comment by royhills** [comment]
I've not seen this before, probably because I've only compiled it with glibc and BSD libc.  I'll need to get an OS that uses musl libc to check this and make the necessary alterations to configure.ac.

It's also worth pointing out that cross compilation hasn't been tested much, and I expect there may be some bugs lurking in that area.

**Comment by rofl0r** [comment]
there are alpine linux and void, which are quite popular, and of course sabotage linux if you want to reproduce it yourself.
the gist of it though that when a configure check uses `exit()` in its code, it must include stdlib.h. an easier fix is probably just to use `return` instead of `exit()`, at least when the code is called from `main()`.
