### ISSUE TITLE
release tags ?

### ISSUE THREAD

**Issue by rofl0r** [royhills/arp-scan#18]
i just noticed that you recently updated NEWS and refer to a version 1.9.5.
there doesnt seem to be a corresponding git tag with a release tarball attached, nor can i find a release tarball apart from 1.9 which is the last tagged release here on github.
am i missing something ?

**Comment by royhills** [comment]
The release numbers correspond to the version number passed to AC_INIT in configure.ac, e.g.

AC_INIT([arp-scan],[1.9.5],[https://github.com/royhills/arp-scan])

I generally increment the third digit of this when a significant change happens, or enough minor changes accumulate.

Releases are normally only two-digit, e.g. 1.8.  These are (or should be) tagged.  But I've not done a release for a while.

**Comment by bjornfor** [comment]
@royhills: I'm confused. So the 1.9.x versions are like beta versions, not really ready for downstream? I'm a packager for Nix/nixpkgs and we currently ship arp-scan-1.9 from 2013. If you'd like to indicate to your users that there is a newer/better version of arp-scan available, please tag it.

**Comment by royhills** [comment]
I've tagged point releases 1.9.2 - 1.9.5 inclusive.

**Comment by bjornfor** [comment]
Thanks!

**Comment by royhills** [comment]
Point release 1.9.6 tagged.
Future tagging and release information will be recorded in issue #41
