### ISSUE TITLE
Could not parse oui

### ISSUE THREAD

**Issue by maxisme** [royhills/arp-scan#22]
Hello I am downloading the `oui` file like this:

```
wget http://standards.ieee.org/regauth/oui/oui.txt
```
and then running:

```
arp-scan --localnet -O oui.txt 
```

which is returning a lot of:

> WARNING: Could not parse oui: ...

**Comment by royhills** [comment]
The get-oui perl script should be used to download and format the IEEE OUI listing.  That will produce a format that arp-scan can parse.

**Comment by maxisme** [comment]
That is weird. Thank you :)
