### ISSUE TITLE
Not work in OSX 10.12.5

### ISSUE THREAD

**Issue by lightbluewind** [royhills/arp-scan#24]
arp-scan --interface=en0 --localnet
Interface: en0, datalink type: EN10MB (Ethernet)
Starting arp-scan 1.9.5 with 512 hosts (https://github.com/royhills/arp-scan)
ERROR: failed to send packet: Bad file descriptor

**Comment by royhills** [comment]
I don't have access to anything running Mac OS X, but arp-scan should work on it using the BPF link layer implementation.  The last version of Mac OS that I know it worked on was snow leopard though; and there have probably been some changes between that and Sierra which you are running.

Could you post the output from ./configure?  That will show which link-layer implementation is being selected.

**Comment by royhills** [comment]
On MacOS Mojave version 10.14.6, configure selects the BPF link layer implementation as expected:

checking build system type... x86_64-apple-darwin18.7.0
...
configure: Using BPF link layer implementation.

arp-scan passes self-tests on this system, but I cannot check sending/receiving packets as I don't have root access.

**Comment by royhills** [comment]
I'm closing this ticket now as I've not been able to reproduce the problem.  Please re-open the issue if this problem still occurs with the latest version. Thanks.
