### ISSUE TITLE
What are the release criteria for 1.10?

### ISSUE THREAD

**Issue by faulesocke** [royhills/arp-scan#28]
There were tons of bug fixes and nice updates since 2013. Would it be possible to make a new release of this software?

The reason I'm asking for is that some linux distributions (void linux in my case) only accept packages in released versions - therefore I would have to pick all the relevant commits and include them as patches manually. Having a new version released would safe me a lot of time.

**Comment by royhills** [comment]
It depends on what void Linux considers a "release".  The latest point release is 1.9.5, as specified by the second argument to AC_INIT in configure.ac:

AC_INIT([arp-scan],[1.9.5],[https://github.com/royhills/arp-scan])

If it only considers major releases, then my my personal requirements for a 1.10 release would be to test the application on all the supported platforms.  Currently, these are:

1. Linux (the development platform, and pretty much guaranteed to work)
2. {Free,Net,Open,Dragonfly}BSD (the pure BSDs)
3. Solaris (I'm not sure if anyone cares about this any more)
4. MacOS X (I find this one hard to test as I don't have a Mac).

But really, for Linux, the git repo should be pretty stable.  Likewise for the pure BSDs.  I just need to test MacOS and decide whether to ignore Solaris.

**Comment by faulesocke** [comment]
Void would accept point releases as well. But would it be possible to have a git tag or a download in the release section for the latest point release? Just so that one can see more easily, that a new (point) release was made?

**Comment by MarcosFouces** [comment]
Hello

In Debian case, we check the release on Github (currently 1.9). Perhaps
you could consider doing point release here.

Greetings,

Marcos

**Comment by bjornfor** [comment]
> The latest point release is 1.9.5, as specified by the second argument to AC_INIT in configure.ac:

[Like the two previous posts say.] Could you create git tags for these point releases, please?

I'm maintaining arp-scan in nixpkgs/NixOS and we currently have version 1.9, because that's the latest release as seen from a packager/end user standpoint (git tags / github releases). Now people are asking to package git master because it has fixes... I think doing that bypasses upstream QA. I'd like upstream, _you_, to tell us which version is the latest and greatest, and not let us users find out by trial and error :-)

**Comment by ilovezfs** [comment]
@royhills yes please tag a 1.9.5 so we can upgrade this in Homebrew. Currently, the lack of a new tag has prevented any upgrades beyond 1.9 in virtually all package managers: https://repology.org/metapackage/arp-scan/versions

**Comment by royhills** [comment]
I've tagged point releases 1.9.2 - 1.9.5 inclusive.

**Comment by ilovezfs** [comment]
@royhills thanks! Voilà https://github.com/Homebrew/homebrew-core/pull/29711

**Comment by faulesocke** [comment]
Thanks a lot!
