### ISSUE TITLE
double entry for 00-01-c8

### ISSUE THREAD

**Issue by R4C3R** [royhills/arp-scan#29]
There is a double entry for 00-01-c8

00-01-C8	CONRAD CORP.
00-01-C8	THOMAS CONRAD CORP.

is that correct?

**Comment by royhills** [comment]
This is caused by duplicate entries in the IEEE OUI listings.  Looking at the file http://standards-oui.ieee.org/oui.txt we see:

00-01-C8   (hex)		THOMAS CONRAD CORP.
00-01-C8   (hex)		CONRAD CORP.

It's not correct, but there's not much we can do about this, as this file is managed by IEEE.
