### ISSUE TITLE
README.md wiki link not valid

### ISSUE THREAD

**Issue by Jahhein** [royhills/arp-scan#32]
Mysql is using an old method of communication that isn't secure therefore the hosting website is denying access.

**Comment by q2dg** [comment]
Well, in fact it gives an connection error

**Comment by grbspltt** [comment]
Currently redirects to main page.

**Comment by bcoles** [comment]
Wiki link works now. It was changed in 347318960b1d137cc0204c6aeb1c3e10aa32b8e6.

**Comment by royhills** [comment]
Closing as problem reported solved in commit https://github.com/royhills/arp-scan/commit/347318960b1d137cc0204c6aeb1c3e10aa32b8e6
