### ISSUE TITLE
Passive ARP scan

### ISSUE THREAD

**Issue by chiro-hiro** [royhills/arp-scan#39]
I'm proposing to have passive scan instead of active, in this mode `arp-scan` will going to sniff on given interface to log all broadcast packets.

It's prevent `arp-scan` to be detected.

**Comment by royhills** [comment]
This would be fairly easy to implement, but it could also be easily implemented by tcpdump/wireshark or another sniffer application.

**Comment by chiro-hiro** [comment]
@royhills I was write a standalone version, it's pretty easy as you said. Hoping `arp-scan` got this feature too. I could use `apr-scan` to detect bad guy who's using ARP poisoning.

**Comment by sonikbhoom** [comment]
Arpwatch may already do what you wish to do.  https://www.kali.org/tools/arpwatch/
