### ISSUE TITLE
Upstream get_hardware_address() to libpcap

### ISSUE THREAD

**Issue by Evils-Devils** [royhills/arp-scan#43]
I'm making [something](https://gitlab.com/evils/clarissa) similar to arp-scan (but under the same license as libpcap, BSD3)
and think it'd be very useful to have a portable way to get an interface's MAC address.

Since arp-scan has portable code for this, and uses libpcap, perhaps you could be convinced to add it to libpcap under their license?

Thanks, Evils.

**Comment by royhills** [comment]
I asked this question on the tcpdump-workers mailing list in January 2011:

https://tcpdump-workers.tcpdump.narkive.com/owJPNTo7/obtaining-interface-ip-address-and-mac-address-with-libpcap

I'd like libpcap to implement a portable get hardware address function, but AFAIK it doesn't have one despite a few people requesting it over the years.

The arp-scan get_hardware_address() function is implemented for packet socket (Linux), BPF (BSD and MacOS) and DLPI (Solaris and others).  It doesn't have a Windows implementation, but that would probably not be too difficult.

If the GPL3 license is preventing you from re-using parts of arp-scan please let me know.

**Comment by Evils-Devils** [comment]
I think putting this functionality in libpcap would require quite a lot of additional pcapng support/standardization. (i doubt they'd want a stray function in there)
So i'll close this issue.  

Wireshark has pcapng write support, but it seems like they don't support the IDB if_MACaddr option.  
So it seems to me your code is the best available.  
I've given making it a reusable stand-alone thing without autoconf a shot [here](https://gitlab.com/evils/get_mac).  

Do i have your permission to publish this under LGPL?  
@viccie30 and @rofl0r seem to also have contributed snippets to the parts i'm reusing from link-packet-socket.c so i wouldn't mind getting their permission too.

**Comment by rofl0r** [comment]
i'm fine with any license.

**Comment by viccie30** [comment]
Go ahead!

**Comment by Evils-Devils** [comment]
@royhills do I have your permission to publish my derived work under LGPLv3?
If so, do I also have permission to reuse subsequent changes to the `link-*.c` files?

**Comment by royhills** [comment]
Yes, I'm happy for you to re-use and publish the code under LGPL license (or any other FOSS license if you subsequently want to change), and to incorprate any future changes from the original source files.

**Comment by Evils-Devils** [comment]
In that case I'll probably go with BSD3.
@viccie30, are you ok with any FOSS license?

**Comment by viccie30** [comment]
As long as it's a FOSS licence, I'm OK with it
