### ISSUE TITLE
no results

### ISSUE THREAD

**Issue by sh1va73** [royhills/arp-scan#44]
arp-scan worked fine always, but from today i dont get any results anymore. This happened after the latest Kali update. It scans but returns no results, no devices are found. Network looks fine, I can ping all devices.
Where do I need to check to fix?
EDIT when I do nmap -sn RANGE then I can find my devices. Only issue is with arp-scan now.

**Comment by royhills** [comment]
This may be a regression caused by the recent changes.

Could you post the operating system and version that you're running arp-scan on, and the output from an arp-scan run? That should help me to reproduce the problem and fix it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sh1va73** [comment]
I was just reading the libpcap issue. I think thats causing the problem.
I am running latest Kali version (issue happened after update of Kali). 
I have arp-scan 1.9.5-1

This is the output:
arp-scan -I eth1 -l
Interface: eth1, datalink type: EN10MB (Ethernet)
Starting arp-scan 1.9.5 with 256 hosts (https://github.com/royhills/arp-scan)

20 packets received by filter, 0 packets dropped by kernel
Ending arp-scan 1.9.5: 256 hosts scanned in 1.885 seconds (135.81 hosts/sec). 0 responded

**Comment by royhills** [comment]
Have you tried using the latest github version of arp-scan? This fixes the issue with libpcap 1.9.1.

I see that kali rolling has libpcap version 1.9.1-2, so I suspect that this is the issue.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sh1va73** [comment]
> Have you tried using the latest github version of arp-scan? This fixes the issue with libpcap 1.9.1. I see that kali rolling has libpcap version 1.9.1-2, so I suspect that this is the issue. Get Outlook for Android<https://aka.ms/ghei36>
> […](#)
> ________________________________ From: sh1va73 <notifications@github.com> Sent: Thursday, October 24, 2019 11:54:51 AM To: royhills/arp-scan <arp-scan@noreply.github.com> Cc: Roy Hills <royhills@hotmail.com>; Comment <comment@noreply.github.com> Subject: Re: [royhills/arp-scan] no results (#44) I was just reading the libpcap issue. I think thats causing the problem. I am running latest Kali version (issue happened after update of Kali). I have arp-scan 1.9.5-1 This is the output: arp-scan -I eth1 -l Interface: eth1, datalink type: EN10MB (Ethernet) Starting arp-scan 1.9.5 with 256 hosts (https://github.com/royhills/arp-scan<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Froyhills%2Farp-scan&data=02%7C01%7C%7Cdf51f0cc088841ea7b3608d75870997d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637075112935214826&sdata=8I0SAiMkRnzDxlfkRq2R70P6B6Lq0p%2BsU53lyGpeLtw%3D&reserved=0>) 20 packets received by filter, 0 packets dropped by kernel Ending arp-scan 1.9.5: 256 hosts scanned in 1.885 seconds (135.81 hosts/sec). 0 responded — You are receiving this because you commented. Reply to this email directly, view it on GitHub<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Froyhills%2Farp-scan%2Fissues%2F44%3Femail_source%3Dnotifications%26email_token%3DABH6HBSIACF2BOQPPYXISY3QQF5HXA5CNFSM4JERHJMKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECETPJY%23issuecomment-545863591&data=02%7C01%7C%7Cdf51f0cc088841ea7b3608d75870997d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637075112935224834&sdata=XitSP5ObShylj2%2BeuNhTrKkBcMNBxTAT%2BYCCDwANols%3D&reserved=0>, or unsubscribe<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABH6HBQ5L3H2BCTTPAAB3LLQQF5HXANCNFSM4JERHJMA&data=02%7C01%7C%7Cdf51f0cc088841ea7b3608d75870997d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637075112935224834&sdata=ns6pwSUIRfPrMg5iRDLQZ8669OXCvmlg18T8SZICIBc%3D&reserved=0>.

I was not succesful in manual install. Can I put old libpcap on my system to make it work?
If so where do i need to put that file?

**Comment by royhills** [comment]
I'm not sure how to install the old version of libpcap on kali rolling.

You should be able to install the latest arp-scan from the git version, but you may need some additional development packages.  Specifically:

build-essential
automake
autoconf
git
libpcap0.8-dev

**Comment by sh1va73** [comment]
Thanks so much for guiding me. I did manual install succesfully and now it is working again.
