### ISSUE TITLE
same issue again 

### ISSUE THREAD

**Issue by sh1va73** [royhills/arp-scan#45]
I have this issue again : https://github.com/royhills/arp-scan/issues/44
This is on a new Kali installation. I tried your suggestions (which worked fine on my other device), but now they dont work. 
Manual installation goes without errors. After install I do arp-scan -- help and i get an error:
bash: /usr/sbin/arp-scan: file or folder does not exist

**Comment by royhills** [comment]
I don't understand the /usr/sbin folder.  The standard configure options will normally put the arp-scan executable in /usr/local/bin when you ran make install.  You should see the name of the destination folder when you run make install.

**Comment by sh1va73** [comment]
Me neither I don't understand. I did nothing special. Just install Kali on a new computer and then I checked arp-scan which was not working. So I followed your guidelines from before and now I get this error.
To make sure: I did remove first the orginal install from Kali

**Comment by sh1va73** [comment]
I did some more testing

/opt/arp-scan# ./arp-scan -h   This command is working.

arp-scan -h is still giving that same error : bash: /usr/sbin/arp-scan: file or folder does not exist

**Comment by sh1va73** [comment]
Not sure what happened, but after updating Kali today the command works again.
