### ISSUE TITLE
Wrong mac reported for 2 interfaces machine

### ISSUE THREAD

**Issue by solsticedhiver** [royhills/arp-scan#47]
arp-scan reports 2 IP but with the same mac when a machine has 2 interfaces. It is expected that each IP is listed with its associated mac.

```
arp-scan -I enp1s0 -l 
Interface: enp1s0, type: EN10MB, MAC: 74:86:7a:xx:xx:xx, IPv4: 192.168.44.115
Starting arp-scan 1.9.7 with 256 hosts (https://github.com/royhills/arp-scan)
[...]
192.168.44.103	bc:14:ef:yy:yy:yy	ITON Technology Limited
192.168.44.149	bc:14:ef:yy:yy:yy	ITON Technology Limited

11 packets received by filter, 0 packets dropped by kernel
Ending arp-scan 1.9.7: 256 hosts scanned in 2.125 seconds (120.47 hosts/sec). 11 responded
```

This machine, an rpi device has one wifi interface and an (usb) ethernet one.

The wifi interface mac is:

    b8:27:eb:zz:zz:zz

with ip as `192.168.44.103`

The expected output is:

    192.168.44.103	b8:27:eb:zz:zz:zz	Raspberry Pi Foundation
    192.168.44.149	bc:14:ef:yy:yy:yy	ITON Technology Limited

**Comment by royhills** [comment]
I think what you are seeing is a side-effect of proxy ARP, where a system will respond to ARP requests for the IP address of any of its interfaces. The mac address will always be the one connected to the segment you are scanning on.

**Comment by solsticedhiver** [comment]
That is one explantion but...

The answer is the same if I use a wifi interface on my latpop to do the scan.

I don't see proxy_arp enabled on that rpi (in `/proc/sys/net/ipv4/conf/<iface>/proxy_arp`) or in the wifi AP (running openwrt)

So the router may be ?

This should be closed ?

**Comment by royhills** [comment]
I think it may be a special case of proxy arp for local interfaces.  I've seen this behaviour on linux systems with two Ethernet interfaces before, although it was a long time ago - maybe in the 2.6 kernel era.  I'm not sure if there is a sysctl/proc control for this type of proxy arp.

No need to close until we've run out of ideas or solved the issue, as these sorts of unexplained issues can sometimes uncover interesting behaviour.

**Comment by royhills** [comment]
This serverfault thread seems to discuss the same behaviour:

https://serverfault.com/questions/834512/why-does-linux-answer-to-arp-on-incorrect-interfaces

**Comment by solsticedhiver** [comment]
Yes that's it.

On the target machine with 2 interfaces, as soon as I set `net.ipv4.all.conf.arp_ignore` to 1 or 2, it works as I excepted it in the output of arp-scan.

That's weird (to me at least) that it is not the default. From the point of view of the output of arp-scan it makes more sense that way. I don't know the internals of the (linux) kernel or it's ipv4 stack ...

**Comment by royhills** [comment]
Well we've both learned something, which is good.  I'll close this ticket now.  Thanks for taking the time to report this behaviour.
