### ISSUE TITLE
Arp-scan documentation disappeared off of nta-monitor.com ?

### ISSUE THREAD

**Issue by varenc** [royhills/arp-scan#52]
[The link to documentation](http://www.nta-monitor.com/wiki/), now just redirects to intertek's the home page.  Can't find docs anywhere on that domain.  What's the correct source for documentation these days?

**Comment by royhills** [comment]
This was caused by the change of website following the acquisition of NTA Monitor Ltd by Intertek Group plc in 2018.

I have restored the wiki from backup at the new URL http://www.royhills.co.uk/wiki/ and have updated the arp-scan documentation accordingly.

**Comment by SuperSandro2000** [comment]
Your wiki has no https.

**Comment by royhills** [comment]
HTTPS support has been added to the www.royhills.co.uk domain
