### ISSUE TITLE
RHEL/CentOS 8 distro

### ISSUE THREAD

**Issue by JonKohler** [royhills/arp-scan#53]
Hey arp-scan'ers - we've got an internal service that uses arp-scan, which we love (good work!). That service is currently using CentOS 7.x userspace.

We're looking to upgrade that service to CentOS 8.x userspace, and I don't see anything in either CentOS 8.x streams or EPEL 8 for arp-scan.

Is that intentional? If so, is the recommended approach to build and install independently? Or is there another yum compatible stream available?

**Comment by royhills** [comment]
Happy to make changes to the code, metadata, dependencies etc. if there's anything blocking a CentOS 8.x package build.

**Comment by jsav0** [comment]
@JonKohler,
Can you run a Docker container run in your environment? If so, I've built one based on alpine, it's quite small, and should work everywhere you can give it the correct permissions. 
 
```
# Basic Usage:
# docker run --net=host -it wfnintr/arp-scan -l
FROM alpine:latest
LABEL maintainer="wfnintr@null.net"
RUN apk add --no-cache --virtual .depends \
	git automake autoconf make gcc g++ libpcap-dev && \
	apk add libpcap && \
	git clone https://github.com/royhills/arp-scan.git && \
	cd arp-scan && \
	autoreconf --install && \
	./configure && \
	make && \
	make install && \
	apk del .depends
ENTRYPOINT ["arp-scan"]
```

**Comment by itamarjp** [comment]
arp-scan is now available in epel8 repository 

https://bugzilla.redhat.com/show_bug.cgi?id=1877425


and can be installed using 

yum -y install arp-scan
or 
dnf -y install arp-scan

**Comment by JonKohler** [comment]
Fabulous! Thanks for tracking that @itamarjp, this is exactly what we were looking for
