### ISSUE TITLE
listing wrong duplicate MAC address for devices with multiple interfaces from same host

### ISSUE THREAD

**Issue by rucareanum** [royhills/arp-scan#56]
Hi royhills,

My setup is a local network with various devices (desktops and laptops) that are connected through either LAN or WIFI or BOTH, each interface with its own IP address from a DHCP server. The arp-scan listing of the localnet has a "bug" as the MAC addresses corresponding to those distinct IPs on the same host are wrongly identified as duplicate of the "previous"/"active" interface.

Here is an edited example from Ubuntu 20.04, but same behaviour is also present on Debian 10 Buster
(please note the wrong identical - generic - MAC addresses "gg:gg:gg:gg:gg:gg" and "nn:nn:nn:nn:nn:nn" listed below from devices with both LAN and WIFI when "simultaneously" connected to same network)

==============================================================
somebody@somewhere:~$ sudo arp-scan -l
Interface: wlp4s0, type: EN10MB, MAC: xx:xx:xx:xx:xx:xx, IPv4: 192.168.2.121
Starting arp-scan 1.9.7 with 256 hosts (https://github.com/royhills/arp-scan)
192.168.2.109	aa:aa:aa:aa:aa:aa	SmartRG, Inc.
192.168.2.118	bb:bb:bb:bb:bb:bb	SmartRG, Inc.
192.168.2.119	cc:cc:cc:cc:cc:cc	Wistron InfoComm(Kunshan)Co.,Ltd.
192.168.2.127	dd:dd:dd:dd:dd:dd	Cisco-Linksys, LLC
192.168.2.134	ee:ee:ee:ee:ee:ee	Hewlett Packard
192.168.2.137	gg:gg:gg:gg:gg:gg	Hewlett Packard
192.168.2.140	gg:gg:gg:gg:gg:gg	Hewlett Packard
192.168.2.141	hh:hh:hh:hh:hh:hh	ASUSTek COMPUTER INC.
192.168.2.126	kk:kk:kk:kk:kk:kk	Apple, Inc.
192.168.2.137	nn:nn:nn:nn:nn:nn	Intel Corporate (DUP: 2)
192.168.2.140	nn:nn:nn:nn:nn:nn	Intel Corporate (DUP: 2)

11 packets received by filter, 0 packets dropped by kernel
Ending arp-scan 1.9.7: 256 hosts scanned in 2.038 seconds (125.61 hosts/sec). 11 responded
==========================================================================
Cheers and Thanks for your insight!

**Comment by royhills** [comment]
That's interesting.  arp-scan will flag a duplicate whenever it receives multiple ARP responses for an IP address.  The code for this is fairly simple, and I've not seen any false positives before, so I expect that arp-scan is receiving two responses from each of the two hosts 192.168.2.137 and 192.168.2.140.  You can check this by running a packet sniffer like wireshark or tcpdump on the host running arp-scan.

As to why the two hosts are responding like this, are the Ethernet and WiFi networks bridged somehow, so a broadcast packet sent to one interface gets seen on both?  Perhaps the dual-homed systems themselves are bridging the interfaces?

I'm not sure that it's a bug, but it's certainly interesting behaviour and I'd be keen to understand why it's happening.

**Comment by rucareanum** [comment]
Thanks for your reply, Roy! I'm a rather newbie when it comes to advanced networking tools, but I'm eager to learn more and willing experiment and learn while "flying", but I would need some expert guidance with precise instructions on what to do step-by-step and what to post or send you directly, if you're willing to assist me to get to the bottom of this very strange situation.

In the meantime, I post hereafter another similar arp-scan listing example (from a Debian laptop this time) which shows even a more "puzzling" behavior, namely several duplicate IP addresses (192.168.2.120 and 192.168.2.121) with different MAC addresses (xx:xx:xx:xx:xx:xx and yy:yy:yy:yy:yy:yy):

====================================================================
somebody@somewhere# sudo arp-scan -l
Interface: wlo1, datalink type: EN10MB (Ethernet)
Starting arp-scan 1.9.5 with 256 hosts (https://github.com/royhills/arp-scan)
192.168.2.109	aa:aa:aa:aa:aa:aa	SmartRG, Inc.
192.168.2.118	bb:bb:bb:bb:bb:bb	SmartRG, Inc.
192.168.2.120	xx:xx:xx:xx:xx:xx	Toshiba
192.168.2.119	cc:cc:cc:cc:cc:cc	Wistron InfoComm(Kunshan)Co.,Ltd.
192.168.2.120	yy:yy:yy:yy:yy:yy	Intel Corporate (DUP: 2)
192.168.2.121	xx:xx:xx:xx:xx:xx	Toshiba
192.168.2.121	yy:yy:yy:yy:yy:yy	Intel Corporate (DUP: 2)
192.168.2.127	dd:dd:dd:dd:dd:dd	Cisco-Linksys, LLC
192.168.2.134	ee:ee:ee:ee:ee:ee	Hewlett Packard
192.168.2.141	hh:hh:hh:hh:hh:hh	ASUSTek COMPUTER INC.

10 packets received by filter, 0 packets dropped by kernel
Ending arp-scan 1.9.5: 256 hosts scanned in 2.864 seconds (89.39 hosts/sec). 10 responded

====================================================================
(I kept the same generic notation as in my previous post in order to facilitate the correlation betwen two, and maybe find some triggering clues for the expert eye)

Another worrysome element that has triggered my attention just now is that the "nmap" listing of my local ntwork has also become "contaminated" and reports the same (wrong) MAC address to the varios IP corresponding to the LAN and Wifi interface. Strange, because it did that correctly until recently (earlier this week) when I have accepted the officially suggested update/upgrade from stable Debian & Ubuntu repositories which included NetworkManager among others, i'm certain. 

There is obviously something "fishy" in here, but i cannot pinpoint what it is nor the extent of it. Thanks a lot for your perseverance, Roy, in maybe getting me on the right track to find the way out of this chaos!

**Comment by royhills** [comment]
I'm not sure why some systems return duplicate ARP responses. I suspect it's because the target system is slow responding to the initial ARP request so gets another request before it has responded to the first, and then responds to both requests.  But that's just a guess.

I wonder if the behaviour your seeing with the Raspberry Pi responding from the "wrong" interface is because the "wrong" address is configured on another interface.  See:

http://www.royhills.co.uk/wiki/index.php/Arp-scan_User_Guide#Discovering_other_interface_addresses

In Linux, this is controlled by the sysctl variables `arp_ignore` and `arp_announce`.

**Comment by royhills** [comment]
arp-scan version `1.10.0` has been released which fixes many bugs and edge cases.  If you are still experiencing unexplained behaviour, I suggest you try this new version which is linked here: https://github.com/royhills/arp-scan/releases/tag/1.10.0
