### ISSUE TITLE
Round-trip time not aligned in a column

### ISSUE THREAD

**Issue by drws** [royhills/arp-scan#57]
The RTT value is separated from the previous output column (OUI manufacturer lookup for example) with a single "hardcoded" tab, which produces a scattered output of RTT (not vertically aligned). The problem is exaggerated by the fact that the manufacturter strings are of varying lengths with variations that can be greater than multiple tabstop lengths.

**Comment by royhills** [comment]
Yes, the output can look horrible.  But some people parse arp-scan output: the simple (if a bit ugly) output makes that fairly easy, and changing the default output would break these scripts.

This could be worked around by adding an "aligned output" option though with a more readable output format.  Not sure what the "better" output format would be though - maybe right aligned with spaces?

Another option would be to move the "RTT=N.NNN ms" before the vendor details.  This is probably what should have been done at the beginning, but again people may be assuming the output format in scripts that parse arp-scan output.

The easiest workaround is probably to do something like:

$ arp-scan [args] | pretty-printing-script

Adding a machine-parsable output format option like XML, JSON or YAML is probably a more useful change overall as it would make script parsing easier and more robust.  We still wouldn't be able to change the default output though, as there are a lot of scripts that depend on this formatting.

**Comment by drws** [comment]
If the output-parsing scripts are written _correctly_, they should interpret sequential whitespace characters as a single delimiter :) Is it possible that some/many of them wouldn't break at all?

The aligned option would be a great addition which could also support selecting between tab, space or any other sensible delimiter. It could, for example, provide options ` ` (space), `  ` (double space, GitHub doesn't print it correctly), `\t` and `\t\t`, where single versions provided a fixed-delimiter operation (currently arp-scan does `\t`) and doubles provided delimiter expansion to produce a pretty terminal output. I guess the default _should_ be the space-expanding option to maintain compatibility with other CLI tools, but then again it wouldn't a problem to keep the default `\t` to maintain compatibility with older versions.

I'm just not sure what you meant by "right-aligned" output? For "pretty" output the column contetns should be left-aligned, except for the RTT with its numeric character.

While moving the RTT column is a good-enough option for prettying the output, it would surely break some scripts and does not provide compatibility option like the additional "align" option does (by keeping the default `\t`). I primarily vote for the align option and propose moving the RTT column as a second option.

**Comment by royhills** [comment]
This and other output format flexibility enhancements will be developed in the output-fields branch. Will update ticket when this feature is present in the branch.
