### ISSUE TITLE
wget: bad header line:     XZBOTalC: rtM; path=/; Max-Age=900

### ISSUE THREAD

**Issue by 62f** [royhills/arp-scan#59]
```wget -c http://www.nta-monitor.com/files/arp-scan/arp-scan-1.9.tar.gz```
Connecting to www.nta-monitor.com (165.160.13.20:80)
Connecting to nta.intertek.com (45.223.17.214:80)
Connecting to nta.intertek.com (45.223.17.214:443)
wget: bad header line:     XZBOTalC: rtM; path=/; Max-Age=900

**Comment by 62f** [comment]
```sudo wget -c http://www.nta-monitor.com/files/arp-scan/arp-scan-1.9.tar.gz```
<details>
Connecting to www.nta-monitor.com (165.160.15.20:80)
Connecting to nta.intertek.com (45.223.17.214:80)
Connecting to nta.intertek.com (45.223.17.214:443)</details>

wget: server returned error: HTTP/1.1 416 Requested Range Not Satisfiable

**Comment by 62f** [comment]
& once more, with 💢:
```sudo wget -c https://www.nta-monitor.com/files/arp-scan/arp-scan-1.9.tar.gz```
<details>
Connecting to www.nta-monitor.com (165.160.15.20:443)</details>

ssl_client: www.nta-monitor.com: handshake failed: Connection reset by peer
wget: error getting response: Invalid argument

**Comment by royhills** [comment]
The nta-monitor website no longer hosts the arp-scan tarballs.  The arp-scan source is available on github with all prior releases tagged, so tarballs can be generated by checking out the appropriate tag and performing a "make dist".

But the arp-scan-1.9 tarball is quite out of date now, and I would suggest that anyone wanting to use arp-scan use the latest source from github if possible.

**Comment by 62f** [comment]
Location: https://nta.intertek.com/ [following]
--2021-05-31 19:59:24--  https://nta.intertek.com/
Connecting to nta.intertek.com (nta.intertek.com)|45.223.17.214|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: 'arp-scan-1.9.tar.gz'

arp-scan-1.9       12.73K  --.-KB/s    in 0.04s   

2021-05-31 19:59:25 (352 KB/s) - 'arp-scan-1.9.tar.gz' saved [13038]

i:~# ls arp-scan-1.9.tar.gz
arp-scan-1.9.tar.gz
iSH-AOK:~# mv arp-scan-1.9.tar.gz /mnt
mv: can't preserve ownership of '/mnt/arp-scan-1.9.tar.gz': Operation not permitted
iSH-AOK:~# cd /mnt
iSH-AOK:/mnt# tar -xf arp-scan-1.9.tar.gz
tar: invalid tar magic
iSH-AOK:/mnt#

**Comment by bcoles** [comment]
> Location: https://nta.intertek.com/ [following] --2021-05-31 19:59:24-- https://nta.intertek.com/ Connecting to nta.intertek.com (nta.intertek.com)|45.223.17.214|:443... connected. HTTP request sent, awaiting response... 200 OK Length: unspecified [text/html] Saving to: 'arp-scan-1.9.tar.gz'
> 
> arp-scan-1.9 12.73K --.-KB/s in 0.04s
> 
> 2021-05-31 19:59:25 (352 KB/s) - 'arp-scan-1.9.tar.gz' saved [13038]

`arp-scan` is hosted in GitHub.

* Clone from GitHub: `git clone https://github.com/royhills/arp-scan`
* or download the old tarball: https://github.com/royhills/arp-scan/archive/refs/tags/1.9.tar.gz


>2021-05-31 19:59:25 (352 KB/s) - 'arp-scan-1.9.tar.gz' saved [13038]

> ```
> iSH-AOK:~# ls arp-scan-1.9.tar.gz arp-scan-1.9.tar.gz
> iSH-AOK:~# mv arp-scan-1.9.tar.gz /mnt
> mv: can't preserve ownership of '/mnt/arp-scan-1.9.tar.gz': Operation not permitted
> iSH-AOK:~# cd /mnt
> iSH-AOK:/mnt# tar -xf arp-scan-1.9.tar.gz tar: invalid tar magic
> ```

Whatever you downloaded is not a valid tarball. arp-scan is significantly larger than 13038 bytes.

```
# ls -la 1.9.tar.gz 
-rw-r--r-- 1 root root 368813 Nov  6 02:18 1.9.tar.gz
# md5sum 1.9.tar.gz 
38cee90a5af3e4ac96a853467ec1c769  1.9.tar.gz
```

**Comment by royhills** [comment]
Version 1.10.0 has been released.  You can download a tarball for this release from here: https://github.com/royhills/arp-scan/releases/tag/1.10.0

This release contains many bug fixes and new features, and I would suggest you try it.  If you still have any issues, please open a new github issue.

Thanks.
