### ISSUE TITLE
libpcap error during compilation

### ISSUE THREAD

**Issue by Buba5473** [royhills/arp-scan#61]
configure: Cannot find pcap library containing pcap_open_live
configure: error: Check that you have libpcap version 1.5 or later installed

I have installed libpcap 1.10.0-1 and libpcap-dev 1.10.0-1 libraries. Please help

**Comment by JackGengChen** [comment]
Hi Buba, I also came across this issue, I wonder if you have solved it yet?

**Comment by Buba5473** [comment]
I decided, but forgot how, unfortunately. Since I did all this under MingW, the answer is unlikely to help you. Under Windows, the application still did not build :(
