### ISSUE TITLE
Communication about running arp-scan as root

### ISSUE THREAD

**Issue by mrquincle** [royhills/arp-scan#68]
The code explains how root, SUID root, or root privileges are required.

```
   fprintf(stdout, "You will need to be root, or arp-scan must be SUID root, in order to run\n");
   fprintf(stdout, "arp-scan, because the functions that it uses to read and write packets\n");
   fprintf(stdout, "require root privilege.\n");
```

It's slightly more subtle than this. I'll just quote:

       For the purpose of performing permission checks, traditional UNIX
       implementations distinguish two categories of processes:
       privileged processes (whose effective user ID is 0, referred to
       as superuser or root), and unprivileged processes (whose
       effective UID is nonzero).  Privileged processes bypass all
       kernel permission checks, while unprivileged processes are
       subject to full permission checking based on the process's
       credentials (usually: effective UID, effective GID, and
       supplementary group list).

       Starting with kernel 2.2, Linux divides the privileges
       traditionally associated with superuser into distinct units,
       known as capabilities, which can be independently enabled and
       disabled.

You can set the capability and then run arp-scan without it being a privileged process:

```
sudo setcap cap_net_raw+ep $(which arp-scan)
arp-scan -l
```

It would be great to reword the text towards users in such a way that running arp-scan with only particular capabilities enabled is considered acceptable (maybe even preferable). Just as a bonus, this can also be done temporarily through `capsh` or `setpriv`.

**Comment by royhills** [comment]
This is linked to the Use Linux Capabilities issue #21 
Any changes will be made to the "capabilities" branch which will be merged into master when tested.

**Comment by mrquincle** [comment]
Okay, this can be closed then, sorry!

**Comment by royhills** [comment]
arp-scan is now capabilities aware and the documentation has been updated accordingly.  Commit 923f123a281139f1ec3daceb1db4bc7317ec6978
