### ISSUE TITLE
Retaining IP address in the output when using `--resolve`

### ISSUE THREAD

**Issue by mattalexx** [royhills/arp-scan#82]
It would be very useful if I could map IP addresses to hostnames when running `arp-scan --resolve`, but the tool seems to be designed to only show me one or the other.

Is there any way the tool could be altered to retain that IP address in the display? Otherwise, my best option is to skip using `--resolve` and just call DNS in a second command.

**Comment by royhills** [comment]
The `--format` (`-F`) option in the latest code on `master` should do what you want.  This was added after the 1.9.8 tag and will be in the next release / tag, but the code is stable and fairly well tested now.

If you specify `--resolve` then the `${name}` field is available so you could use:

```
$ ./arp-scan --localnet --resolve --format='${ip}\t${name}\t${mac}\t${vendor}'
Interface: ens33, type: EN10MB, MAC: 00:0c:29:d3:97:e8, IPv4: 192.168.14.128
Starting arp-scan 1.9.9 with 256 hosts (https://github.com/royhills/arp-scan)
192.168.14.2    test2.home.arpa 00:50:56:e4:9a:83       VMware, Inc.
192.168.14.1    test.home.arpa  00:50:56:c0:00:08       VMware, Inc.
192.168.14.254  192.168.14.254  00:50:56:fc:ca:ea       VMware, Inc.

5 packets received by filter, 0 packets dropped by kernel
Ending arp-scan 1.9.9: 256 hosts scanned in 1.922 seconds (133.19 hosts/sec). 3 responded
```

You could also use field widths if you need a tidy output if the hostname lengths vary, e.g:

```
$ ./arp-scan --localnet --resolve --format='${ip;-15}|${name;-20}|${mac}|${vendor}'
Interface: ens33, type: EN10MB, MAC: 00:0c:29:d3:97:e8, IPv4: 192.168.14.128
Starting arp-scan 1.9.9 with 256 hosts (https://github.com/royhills/arp-scan)
192.168.14.2   |test2.home.arpa     |00:50:56:e4:9a:83|VMware, Inc.
192.168.14.1   |test.home.arpa      |00:50:56:c0:00:08|VMware, Inc.
192.168.14.254 |192.168.14.254      |00:50:56:fc:ca:ea|VMware, Inc.

5 packets received by filter, 0 packets dropped by kernel
Ending arp-scan 1.9.9: 256 hosts scanned in 1.870 seconds (136.90 hosts/sec). 3 responded
```

**Comment by mattalexx** [comment]
Excellent! thanks for this tool
