### ISSUE TITLE
Doesn't work with Back To My Mac active (utun0, OS X 10.11.3)

### ISSUE THREAD

**Issue by JayBrown** [royhills/arp-scan#9]
When the utun0 interface is active, which apparently belongs to OS X Back To My Mac (see ifconfig), arp-scan doesn't work, even if you use your default gateway's router IP address accessed via en1 or en0. arp-scan just doesn't comply and wants to penetrate utun0. And so I get the error message "ERROR: Could not obtain MAC address for interface utun0". When I switch off Back To My Mac in System Preferences > iCloud, the utun0 interface disappears, and arp-scan works normally again. Well, this is clearly a bug.

**Comment by royhills** [comment]
You should be able to select the interface to use with the --interface flag, e.g. "arp-scan --interface=en0".  Does that still give the error?

If you don't specify an interface with --interface, the default interface selection is done by the pcap_lookupdev() function from libpcap.  If that's picking an unsuitable interface, then it could be a bug in libpcap, or it could be that arp-scan should use a different function.

**Comment by JayBrown** [comment]
Oh, damn. Thank you… didn't know about the --interface option. Must have overlooked it in the man page.
